<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('countries')->insert([
            ['Country_code' => 'AF', 'Name' => 'Afghanistan', 'Nationality' => 'Afghan'],
            ['Country_code' => 'AL', 'Name' => 'Albania', 'Nationality' => 'Albanian'],
            ['Country_code' => 'AX', 'Name' => 'Aland Islands', 'Nationality' => 'Aland Islander'],
            ['Country_code' => 'DZ', 'Name' => 'Algeria', 'Nationality' => 'Algerian'],
            ['Country_code' => 'AS', 'Name' => 'American Samoa', 'Nationality' => 'American Samoan'],
            ['Country_code' => 'AD', 'Name' => 'Andorra', 'Nationality' => 'Andorran'],
            ['Country_code' => 'AO', 'Name' => 'Angola', 'Nationality' => 'Angolan'],
            ['Country_code' => 'AI', 'Name' => 'Anguilla', 'Nationality' => 'Anguillan'],
            ['Country_code' => 'AQ', 'Name' => 'Antarctica', 'Nationality' => 'Antarctican'],
            ['Country_code' => 'AG', 'Name' => 'Antigua and Barbuda', 'Nationality' => 'Antiguan'],
            ['Country_code' => 'AR', 'Name' => 'Argentina', 'Nationality' => 'Argentinian'],
            ['Country_code' => 'AM', 'Name' => 'Armenia', 'Nationality' => 'Armenian'],
            ['Country_code' => 'AW', 'Name' => 'Aruba', 'Nationality' => 'Aruban'],
            ['Country_code' => 'AU', 'Name' => 'Australia', 'Nationality' => 'Australian'],
            ['Country_code' => 'AT', 'Name' => 'Austria', 'Nationality' => 'Austrian'],
            ['Country_code' => 'AZ', 'Name' => 'Azerbaijan', 'Nationality' => 'Azerbaijani'],
            ['Country_code' => 'BS', 'Name' => 'Bahamas', 'Nationality' => 'Bahamian'],
            ['Country_code' => 'BH', 'Name' => 'Bahrain', 'Nationality' => 'Bahraini'],
            ['Country_code' => 'BD', 'Name' => 'Bangladesh', 'Nationality' => 'Bangladeshi'],
            ['Country_code' => 'BB', 'Name' => 'Barbados', 'Nationality' => 'Barbadian'],
            ['Country_code' => 'BY', 'Name' => 'Belarus', 'Nationality' => 'Belarusian'],
            ['Country_code' => 'BE', 'Name' => 'Belgium', 'Nationality' => 'Belgian'],
            ['Country_code' => 'BZ', 'Name' => 'Belize', 'Nationality' => 'Belizean'],
            ['Country_code' => 'BJ', 'Name' => 'Benin', 'Nationality' => 'Beninese'],
            ['Country_code' => 'BL', 'Name' => 'Saint Barthelemy', 'Nationality' => 'Saint Barthelmian'],
            ['Country_code' => 'BM', 'Name' => 'Bermuda', 'Nationality' => 'Bermudan'],
            ['Country_code' => 'BT', 'Name' => 'Bhutan', 'Nationality' => 'Bhutanese'],
            ['Country_code' => 'BO', 'Name' => 'Bolivia', 'Nationality' => 'Bolivian'],
            ['Country_code' => 'BA', 'Name' => 'Bosnia and Herzegovina', 'Nationality' => 'Bosnian / Herzegovinian'],
            ['Country_code' => 'BW', 'Name' => 'Botswana', 'Nationality' => 'Botswanan'],
            ['Country_code' => 'BV', 'Name' => 'Bouvet Island', 'Nationality' => 'Bouvetian'],
            ['Country_code' => 'BR', 'Name' => 'Brazil', 'Nationality' => 'Brazilian'],
            ['Country_code' => 'IO', 'Name' => 'British Indian Ocean Territory', 'Nationality' => 'British Indian Ocean Territory'],
            ['Country_code' => 'BN', 'Name' => 'Brunei Darussalam', 'Nationality' => 'Bruneian'],
            ['Country_code' => 'BG', 'Name' => 'Bulgaria', 'Nationality' => 'Bulgarian'],
            ['Country_code' => 'BF', 'Name' => 'Burkina Faso', 'Nationality' => 'Burkinabe'],
            ['Country_code' => 'BI', 'Name' => 'Burundi', 'Nationality' => 'Burundian'],
            ['Country_code' => 'KH', 'Name' => 'Cambodia', 'Nationality' => 'Cambodian'],
            ['Country_code' => 'CM', 'Name' => 'Cameroon', 'Nationality' => 'Cameroonian'],
            ['Country_code' => 'CA', 'Name' => 'Canada', 'Nationality' => 'Canadian'],
            ['Country_code' => 'CV', 'Name' => 'Cape Verde', 'Nationality' => 'Cape Verdean'],
            ['Country_code' => 'KY', 'Name' => 'Cayman Islands', 'Nationality' => 'Caymanian'],
            ['Country_code' => 'CF', 'Name' => 'Central African Republic', 'Nationality' => 'Central African'],
            ['Country_code' => 'TD', 'Name' => 'Chad', 'Nationality' => 'Chadian'],
            ['Country_code' => 'CL', 'Name' => 'Chile', 'Nationality' => 'Chilean'],
            ['Country_code' => 'CN', 'Name' => 'China', 'Nationality' => 'Chinese'],
            ['Country_code' => 'CX', 'Name' => 'Christmas Island', 'Nationality' => 'Christmas Islander'],
            ['Country_code' => 'CC', 'Name' => 'Cocos (Keeling) Islands', 'Nationality' => 'Cocos Islander'],
            ['Country_code' => 'CO', 'Name' => 'Colombia', 'Nationality' => 'Colombian'],
            ['Country_code' => 'KM', 'Name' => 'Comoros', 'Nationality' => 'Comorian'],
            ['Country_code' => 'CG', 'Name' => 'Congo', 'Nationality' => 'Congolese'],
            ['Country_code' => 'CK', 'Name' => 'Cook Islands', 'Nationality' => 'Cook Islander'],
            ['Country_code' => 'CR', 'Name' => 'Costa Rica', 'Nationality' => 'Costa Rican'],
            ['Country_code' => 'HR', 'Name' => 'Croatia', 'Nationality' => 'Croatian'],
            ['Country_code' => 'CU', 'Name' => 'Cuba', 'Nationality' => 'Cuban'],
            ['Country_code' => 'CY', 'Name' => 'Cyprus', 'Nationality' => 'Cypriot'],
            ['Country_code' => 'CW', 'Name' => 'Curaçao', 'Nationality' => 'Curacian'],
            ['Country_code' => 'CZ', 'Name' => 'Czech Republic', 'Nationality' => 'Czech'],
            ['Country_code' => 'DK', 'Name' => 'Denmark', 'Nationality' => 'Danish'],
            ['Country_code' => 'DJ', 'Name' => 'Djibouti', 'Nationality' => 'Djiboutian'],
            ['Country_code' => 'DM', 'Name' => 'Dominica', 'Nationality' => 'Dominican'],
            ['Country_code' => 'DO', 'Name' => 'Dominican Republic', 'Nationality' => 'Dominican'],
            ['Country_code' => 'EC', 'Name' => 'Ecuador', 'Nationality' => 'Ecuadorian'],
            ['Country_code' => 'EG', 'Name' => 'Egypt', 'Nationality' => 'Egyptian'],
            ['Country_code' => 'SV', 'Name' => 'El Salvador', 'Nationality' => 'Salvadoran'],
            ['Country_code' => 'GQ', 'Name' => 'Equatorial Guinea', 'Nationality' => 'Equatorial Guinean'],
            ['Country_code' => 'ER', 'Name' => 'Eritrea', 'Nationality' => 'Eritrean'],
            ['Country_code' => 'EE', 'Name' => 'Estonia', 'Nationality' => 'Estonian'],
            ['Country_code' => 'ET', 'Name' => 'Ethiopia', 'Nationality' => 'Ethiopian'],
            ['Country_code' => 'FK', 'Name' => 'Falkland Islands (Malvinas)', 'Nationality' => 'Falkland Islander'],
            ['Country_code' => 'FO', 'Name' => 'Faroe Islands', 'Nationality' => 'Faroese'],
            ['Country_code' => 'FJ', 'Name' => 'Fiji', 'Nationality' => 'Fijian'],
            ['Country_code' => 'FI', 'Name' => 'Finland', 'Nationality' => 'Finnish'],
            ['Country_code' => 'FR', 'Name' => 'France', 'Nationality' => 'French'],
            ['Country_code' => 'GF', 'Name' => 'French Guiana', 'Nationality' => 'French Guianese'],
            ['Country_code' => 'PF', 'Name' => 'French Polynesia', 'Nationality' => 'French Polynesian'],
            ['Country_code' => 'TF', 'Name' => 'French Southern and Antarctic Lands', 'Nationality' => 'French'],
            ['Country_code' => 'GA', 'Name' => 'Gabon', 'Nationality' => 'Gabonese'],
            ['Country_code' => 'GM', 'Name' => 'Gambia', 'Nationality' => 'Gambian'],
            ['Country_code' => 'GE', 'Name' => 'Georgia', 'Nationality' => 'Georgian'],
            ['Country_code' => 'DE', 'Name' => 'Germany', 'Nationality' => 'German'],
            ['Country_code' => 'GH', 'Name' => 'Ghana', 'Nationality' => 'Ghanaian'],
            ['Country_code' => 'GI', 'Name' => 'Gibraltar', 'Nationality' => 'Gibraltar'],
            ['Country_code' => 'GG', 'Name' => 'Guernsey', 'Nationality' => 'Guernsian'],
            ['Country_code' => 'GR', 'Name' => 'Greece', 'Nationality' => 'Greek'],
            ['Country_code' => 'GL', 'Name' => 'Greenland', 'Nationality' => 'Greenlandic'],
            ['Country_code' => 'GD', 'Name' => 'Grenada', 'Nationality' => 'Grenadian'],
            ['Country_code' => 'GP', 'Name' => 'Guadeloupe', 'Nationality' => 'Guadeloupe'],
            ['Country_code' => 'GU', 'Name' => 'Guam', 'Nationality' => 'Guamanian'],
            ['Country_code' => 'GT', 'Name' => 'Guatemala', 'Nationality' => 'Guatemalan'],
            ['Country_code' => 'GN', 'Name' => 'Guinea', 'Nationality' => 'Guinean'],
            ['Country_code' => 'GW', 'Name' => 'Guinea-Bissau', 'Nationality' => 'Guinea-Bissauan'],
            ['Country_code' => 'GY', 'Name' => 'Guyana', 'Nationality' => 'Guyanese'],
            ['Country_code' => 'HT', 'Name' => 'Haiti', 'Nationality' => 'Haitian'],
            ['Country_code' => 'HM', 'Name' => 'Heard and Mc Donald Islands', 'Nationality' => 'Heard and Mc Donald Islanders'],
            ['Country_code' => 'HN', 'Name' => 'Honduras', 'Nationality' => 'Honduran'],
            ['Country_code' => 'HK', 'Name' => 'Hong Kong', 'Nationality' => 'Hongkongese'],
            ['Country_code' => 'HU', 'Name' => 'Hungary', 'Nationality' => 'Hungarian'],
            ['Country_code' => 'IS', 'Name' => 'Iceland', 'Nationality' => 'Icelandic'],
            ['Country_code' => 'IN', 'Name' => 'India', 'Nationality' => 'Indian'],
            ['Country_code' => 'IM', 'Name' => 'Isle of Man', 'Nationality' => 'Manx'],
            ['Country_code' => 'ID', 'Name' => 'Indonesia', 'Nationality' => 'Indonesian'],
            ['Country_code' => 'IR', 'Name' => 'Iran', 'Nationality' => 'Iranian'],
            ['Country_code' => 'IQ', 'Name' => 'Iraq', 'Nationality' => 'Iraqi'],
            ['Country_code' => 'IE', 'Name' => 'Ireland', 'Nationality' => 'Irish'],
            ['Country_code' => 'IL', 'Name' => 'Israel', 'Nationality' => 'Israeli'],
            ['Country_code' => 'IT', 'Name' => 'Italy', 'Nationality' => 'Italian'],
            ['Country_code' => 'CI', 'Name' => 'Ivory Coast', 'Nationality' => 'Ivory Coastian'],
            ['Country_code' => 'JE', 'Name' => 'Jersey', 'Nationality' => 'Jersian'],
            ['Country_code' => 'JM', 'Name' => 'Jamaica', 'Nationality' => 'Jamaican'],
            ['Country_code' => 'JP', 'Name' => 'Japan', 'Nationality' => 'Japanese'],
            ['Country_code' => 'JO', 'Name' => 'Jordan', 'Nationality' => 'Jordanian'],
            ['Country_code' => 'KZ', 'Name' => 'Kazakhstan', 'Nationality' => 'Kazakh'],
            ['Country_code' => 'KE', 'Name' => 'Kenya', 'Nationality' => 'Kenyan'],
            ['Country_code' => 'KI', 'Name' => 'Kiribati', 'Nationality' => 'I-Kiribati'],
            ['Country_code' => 'KP', 'Name' => 'Korea(North Korea)', 'Nationality' => 'North Korean'],
            ['Country_code' => 'KR', 'Name' => 'Korea(South Korea)', 'Nationality' => 'South Korean'],
            ['Country_code' => 'XK', 'Name' => 'Kosovo', 'Nationality' => 'Kosovar'],
            ['Country_code' => 'KW', 'Name' => 'Kuwait', 'Nationality' => 'Kuwaiti'],
            ['Country_code' => 'KG', 'Name' => 'Kyrgyzstan', 'Nationality' => 'Kyrgyzstani'],
            ['Country_code' => 'LA', 'Name' => 'Lao PDR', 'Nationality' => 'Laotian'],
            ['Country_code' => 'LV', 'Name' => 'Latvia', 'Nationality' => 'Latvian'],
            ['Country_code' => 'LB', 'Name' => 'Lebanon', 'Nationality' => 'Lebanese'],
            ['Country_code' => 'LS', 'Name' => 'Lesotho', 'Nationality' => 'Basotho'],
            ['Country_code' => 'LR', 'Name' => 'Liberia', 'Nationality' => 'Liberian'],
            ['Country_code' => 'LY', 'Name' => 'Libya', 'Nationality' => 'Libyan'],
            ['Country_code' => 'LI', 'Name' => 'Liechtenstein', 'Nationality' => 'Liechtenstein'],
            ['Country_code' => 'LT', 'Name' => 'Lithuania', 'Nationality' => 'Lithuanian'],
            ['Country_code' => 'LU', 'Name' => 'Luxembourg', 'Nationality' => 'Luxembourger'],
            ['Country_code' => 'LK', 'Name' => 'Sri Lanka', 'Nationality' => 'Sri Lankian'],
            ['Country_code' => 'MO', 'Name' => 'Macau', 'Nationality' => 'Macanese'],
            ['Country_code' => 'MK', 'Name' => 'Macedonia', 'Nationality' => 'Macedonian'],
            ['Country_code' => 'MG', 'Name' => 'Madagascar', 'Nationality' => 'Malagasy'],
            ['Country_code' => 'MW', 'Name' => 'Malawi', 'Nationality' => 'Malawian'],
            ['Country_code' => 'MY', 'Name' => 'Malaysia', 'Nationality' => 'Malaysian'],
            ['Country_code' => 'MV', 'Name' => 'Maldives', 'Nationality' => 'Maldivian'],
            ['Country_code' => 'ML', 'Name' => 'Mali', 'Nationality' => 'Malian'],
            ['Country_code' => 'MT', 'Name' => 'Malta', 'Nationality' => 'Maltese'],
            ['Country_code' => 'MH', 'Name' => 'Marshall Islands', 'Nationality' => 'Marshallese'],
            ['Country_code' => 'MQ', 'Name' => 'Martinique', 'Nationality' => 'Martiniquais'],
            ['Country_code' => 'MR', 'Name' => 'Mauritania', 'Nationality' => 'Mauritanian'],
            ['Country_code' => 'MU', 'Name' => 'Mauritius', 'Nationality' => 'Mauritian'],
            ['Country_code' => 'YT', 'Name' => 'Mayotte', 'Nationality' => 'Mahoran'],
            ['Country_code' => 'MX', 'Name' => 'Mexico', 'Nationality' => 'Mexican'],
            ['Country_code' => 'FM', 'Name' => 'Micronesia', 'Nationality' => 'Micronesian'],
            ['Country_code' => 'MD', 'Name' => 'Moldova', 'Nationality' => 'Moldovan'],
            ['Country_code' => 'MC', 'Name' => 'Monaco', 'Nationality' => 'Monacan'],
            ['Country_code' => 'MN', 'Name' => 'Mongolia', 'Nationality' => 'Mongolian'],
            ['Country_code' => 'ME', 'Name' => 'Montenegro', 'Nationality' => 'Montenegrin'],
            ['Country_code' => 'MS', 'Name' => 'Montserrat', 'Nationality' => 'Montserratian'],
            ['Country_code' => 'MA', 'Name' => 'Morocco', 'Nationality' => 'Moroccan'],
            ['Country_code' => 'MZ', 'Name' => 'Mozambique', 'Nationality' => 'Mozambican'],
            ['Country_code' => 'MM', 'Name' => 'Myanmar', 'Nationality' => 'Myanmarian'],
            ['Country_code' => 'NA', 'Name' => 'Namibia', 'Nationality' => 'Namibian'],
            ['Country_code' => 'NR', 'Name' => 'Nauru', 'Nationality' => 'Nauruan'],
            ['Country_code' => 'NP', 'Name' => 'Nepal', 'Nationality' => 'Nepalese'],
            ['Country_code' => 'NL', 'Name' => 'Netherlands', 'Nationality' => 'Dutch'],
            ['Country_code' => 'AN', 'Name' => 'Netherlands Antilles', 'Nationality' => 'Dutch Antilier'],
            ['Country_code' => 'NC', 'Name' => 'New Caledonia', 'Nationality' => 'New Caledonian'],
            ['Country_code' => 'NZ', 'Name' => 'New Zealand', 'Nationality' => 'New Zealander'],
            ['Country_code' => 'NI', 'Name' => 'Nicaragua', 'Nationality' => 'Nicaraguan'],
            ['Country_code' => 'NE', 'Name' => 'Niger', 'Nationality' => 'Nigerien'],
            ['Country_code' => 'NG', 'Name' => 'Nigeria', 'Nationality' => 'Nigerian'],
            ['Country_code' => 'NU', 'Name' => 'Niue', 'Nationality' => 'Niuean'],
            ['Country_code' => 'NF', 'Name' => 'Norfolk Island', 'Nationality' => 'Norfolk Islander'],
            ['Country_code' => 'MP', 'Name' => 'Northern Mariana Islands', 'Nationality' => 'Northern Marianan'],
            ['Country_code' => 'NO', 'Name' => 'Norway', 'Nationality' => 'Norwegian'],
            ['Country_code' => 'OM', 'Name' => 'Oman', 'Nationality' => 'Omani'],
            ['Country_code' => 'PK', 'Name' => 'Pakistan', 'Nationality' => 'Pakistani'],
            ['Country_code' => 'PW', 'Name' => 'Palau', 'Nationality' => 'Palauan'],
            ['Country_code' => 'PS', 'Name' => 'Palestine', 'Nationality' => 'Palestinian'],
            ['Country_code' => 'PA', 'Name' => 'Panama', 'Nationality' => 'Panamanian'],
            ['Country_code' => 'PG', 'Name' => 'Papua New Guinea', 'Nationality' => 'Papua New Guinean'],
            ['Country_code' => 'PY', 'Name' => 'Paraguay', 'Nationality' => 'Paraguayan'],
            ['Country_code' => 'PE', 'Name' => 'Peru', 'Nationality' => 'Peruvian'],
            ['Country_code' => 'PH', 'Name' => 'Philippines', 'Nationality' => 'Filipino'],
            ['Country_code' => 'PN', 'Name' => 'Pitcairn', 'Nationality' => 'Pitcairn Islander'],
            ['Country_code' => 'PL', 'Name' => 'Poland', 'Nationality' => 'Polish'],
            ['Country_code' => 'PT', 'Name' => 'Portugal', 'Nationality' => 'Portuguese'],
            ['Country_code' => 'PR', 'Name' => 'Puerto Rico', 'Nationality' => 'Puerto Rican'],
            ['Country_code' => 'QA', 'Name' => 'Qatar', 'Nationality' => 'Qatari'],
            ['Country_code' => 'RE', 'Name' => 'Reunion Island', 'Nationality' => 'Reunionese'],
            ['Country_code' => 'RO', 'Name' => 'Romania', 'Nationality' => 'Romanian'],
            ['Country_code' => 'RU', 'Name' => 'Russian', 'Nationality' => 'Russian'],
            ['Country_code' => 'RW', 'Name' => 'Rwanda', 'Nationality' => 'Rwandan'],
            ['Country_code' => 'KN', 'Name' => 'Saint Kitts and Nevis', 'Nationality' => 'Kittitian/Nevisian'],
            ['Country_code' => 'MF', 'Name' => 'Saint Martin (French part)', 'Nationality' => 'St. Martian(French)'],
            ['Country_code' => 'SX', 'Name' => 'Sint Maarten (Dutch part)', 'Nationality' => 'St. Martian(Dutch)'],
            ['Country_code' => 'LC', 'Name' => 'Saint Pierre and Miquelon', 'Nationality' => 'St. Pierre and Miquelon'],
            ['Country_code' => 'VC', 'Name' => 'Saint Vincent and the Grenadines', 'Nationality' => 'Saint Vincent and the Grenadines'],
            ['Country_code' => 'WS', 'Name' => 'Samoa', 'Nationality' => 'Samoan'],
            ['Country_code' => 'SM', 'Name' => 'San Marino', 'Nationality' => 'Sammarinese'],
            ['Country_code' => 'ST', 'Name' => 'Sao Tome and Principe', 'Nationality' => 'Sao Tomean'],
            ['Country_code' => 'SA', 'Name' => 'Saudi Arabia', 'Nationality' => 'Saudi Arabian'],
            ['Country_code' => 'SN', 'Name' => 'Senegal', 'Nationality' => 'Senegalese'],
            ['Country_code' => 'RS', 'Name' => 'Serbia', 'Nationality' => 'Serbian'],
            ['Country_code' => 'SC', 'Name' => 'Seychelles', 'Nationality' => 'Seychellois'],
            ['Country_code' => 'SL', 'Name' => 'Sierra Leone', 'Nationality' => 'Sierra Leonean'],
            ['Country_code' => 'SG', 'Name' => 'Singapore', 'Nationality' => 'Singaporean'],
            ['Country_code' => 'SK', 'Name' => 'Slovakia', 'Nationality' => 'Slovak'],
            ['Country_code' => 'SI', 'Name' => 'Slovenia', 'Nationality' => 'Slovenian'],
            ['Country_code' => 'SB', 'Name' => 'Solomon Islands', 'Nationality' => 'Solomon Island'],
            ['Country_code' => 'SO', 'Name' => 'Somalia', 'Nationality' => 'Somali'],
            ['Country_code' => 'ZA', 'Name' => 'South Africa', 'Nationality' => 'South African'],
            ['Country_code' => 'GS', 'Name' => 'South Georgia and the South Sandwich', 'Nationality' => 'South Georgia and the South Sandwich'],
            ['Country_code' => 'SS', 'Name' => 'South Sudan', 'Nationality' => 'South Sudanese'],
            ['Country_code' => 'ES', 'Name' => 'Spain', 'Nationality' => 'Spanish'],
            ['Country_code' => 'SH', 'Name' => 'Saint Helena', 'Nationality' => 'St. Helenian'],
            ['Country_code' => 'SD', 'Name' => 'Sudan', 'Nationality' => 'Sudanese'],
            ['Country_code' => 'SR', 'Name' => 'Suriname', 'Nationality' => 'Surinamese'],
            ['Country_code' => 'SJ', 'Name' => 'Svalbard and Jan Mayen', 'Nationality' => 'Svalbardian/Jan Mayenian'],
            ['Country_code' => 'SZ', 'Name' => 'Swaziland', 'Nationality' => 'Swazi'],
            ['Country_code' => 'SE', 'Name' => 'Sweden', 'Nationality' => 'Swedish'],
            ['Country_code' => 'CH', 'Name' => 'Switzerland', 'Nationality' => 'Swiss'],
            ['Country_code' => 'SY', 'Name' => 'Syria', 'Nationality' => 'Syrian'],
            ['Country_code' => 'TW', 'Name' => 'Taiwan', 'Nationality' => 'Taiwanese'],
            ['Country_code' => 'TJ', 'Name' => 'Tajikistan', 'Nationality' => 'Tajikistani'],
            ['Country_code' => 'TZ', 'Name' => 'Tanzania', 'Nationality' => 'Tanzanian'],
            ['Country_code' => 'TH', 'Name' => 'Thailand', 'Nationality' => 'Thai'],
            ['Country_code' => 'TL', 'Name' => 'Timor-Leste', 'Nationality' => 'Timor-Lestian'],
            ['Country_code' => 'TG', 'Name' => 'Togo', 'Nationality' => 'Togolese'],
            ['Country_code' => 'TK', 'Name' => 'Tokelau', 'Nationality' => 'Tokelaian'],
            ['Country_code' => 'TO', 'Name' => 'Tonga', 'Nationality' => 'Tongan'],
            ['Country_code' => 'TT', 'Name' => 'Trinidad and Tobago', 'Nationality' => 'Trinidadian/Tobagonian'],
            ['Country_code' => 'TN', 'Name' => 'Tunisia', 'Nationality' => 'Tunisian'],
            ['Country_code' => 'TR', 'Name' => 'Turkey', 'Nationality' => 'Turkish'],
            ['Country_code' => 'TM', 'Name' => 'Turkmenistan', 'Nationality' => 'Turkmen'],
            ['Country_code' => 'TC', 'Name' => 'Turks and Caicos Islands', 'Nationality' => 'Turks and Caicos Islands'],
            ['Country_code' => 'TV', 'Name' => 'Tuvalu', 'Nationality' => 'Tuvaluan'],
            ['Country_code' => 'UG', 'Name' => 'Uganda', 'Nationality' => 'Ugandan'],
            ['Country_code' => 'UA', 'Name' => 'Ukraine', 'Nationality' => 'Ukrainian'],
            ['Country_code' => 'AE', 'Name' => 'United Arab Emirates', 'Nationality' => 'Emirati'],
            ['Country_code' => 'GB', 'Name' => 'United Kingdom', 'Nationality' => 'British'],
            ['Country_code' => 'US', 'Name' => 'United States', 'Nationality' => 'American'],
            ['Country_code' => 'UM', 'Name' => 'US Minor Outlying Islands', 'Nationality' => 'US Minor Outlying Islander'],
            ['Country_code' => 'UY', 'Name' => 'Uruguay', 'Nationality' => 'Uruguayan'],
            ['Country_code' => 'UZ', 'Name' => 'Uzbekistan', 'Nationality' => 'Uzbek'],
            ['Country_code' => 'VU', 'Name' => 'Vanuatu', 'Nationality' => 'Vanuatuan'],
            ['Country_code' => 'VE', 'Name' => 'Venezuela', 'Nationality' => 'Venezuelan'],
            ['Country_code' => 'VN', 'Name' => 'Vietnam', 'Nationality' => 'Vietnamese'],
            ['Country_code' => 'VI', 'Name' => 'Virgin Islands (U.S.)', 'Nationality' => 'American Virgin Islander'],
            ['Country_code' => 'VA', 'Name' => 'Vatican City', 'Nationality' => 'Vatican'],
            ['Country_code' => 'WF', 'Name' => 'Wallis and Futuna Islands', 'Nationality' => 'Wallisian/Futunan'],
            ['Country_code' => 'EH', 'Name' => 'Western Sahara', 'Nationality' => 'Sahrawian'],
            ['Country_code' => 'YE', 'Name' => 'Yemen', 'Nationality' => 'Yemeni'],
            ['Country_code' => 'ZM', 'Name' => 'Zambia', 'Nationality' => 'Zambian'],
            ['Country_code' => 'ZW', 'Name' => 'Zimbabwe', 'Nationality' => 'Zimbabwean']
        ]);
    }
}
